# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: xxx-www-eee-org
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: book-review-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: category

# try changing default to random
stages:
  prod:
    params:
      tableName: "category-table-${sls:stage}"

  default:
    params:
      tableName: "category-table-${sls:stage}"

#service wide settings (for all functions)
provider:
  name: aws
  region: ap-south-1
  versionFunctions: false
  runtime: nodejs20.x
  httpApi:
    cors: true
    authorizers:
      cognitoJwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_xxxxx
        audience:
          - xxxx-ffff-dsdsdsd-rewqsa
  ## permissions for service-wide functions to access DynamoDB
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [CategoryTable, Arn]
  environment:
    CATEGORY_TABLE: ${param:tableName}

functions:
  getCategoryList:
    handler: categoryList.getCategoryList
    events:
      - httpApi:
          path: /category
          method: GET
          authorizer:
            name: cognitoJwtAuthorizer
  createCategory:
    handler: categoryCreate.createCategory
    events:
      - httpApi:
          path: /category
          method: POST
          authorizer:
            name: cognitoJwtAuthorizer

## resources needed for lambda functions
## database to store data
resources:
  Resources:
    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: categoryId
            AttributeType: S
        KeySchema:
          - AttributeName: categoryId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
